export type ChecklistSection = 'online' | 'physical';

export interface ChecklistDoc {
  id: string;
  section: ChecklistSection;
  name: string;
  mandatory: boolean;
  notes: string;
  format: string;
  fileSize: string | null;
  states: string[];       // empty = all states
  categories: string[];   // empty = all categories
  counsellingTypes: string[]; // empty = all types
}

export const CHECKLIST_DOCS: ChecklistDoc[] = [
  // ───────────── ONLINE REGISTRATION DOCUMENTS ─────────────
  {
    id: 'ol-1',
    section: 'online',
    name: 'NEET UG Scorecard / Rank Letter',
    mandatory: true,
    notes: 'Download the official scorecard from nta.ac.in. Both scorecard and rank letter are needed. Ensure the PDF is clear and legible.',
    format: 'PDF / JPEG',
    fileSize: 'Max 500 KB',
    states: [],
    categories: [],
    counsellingTypes: [],
  },
  {
    id: 'ol-2',
    section: 'online',
    name: 'NEET UG Admit Card',
    mandatory: true,
    notes: 'The admit card used during the NEET exam. Must show photograph, roll number, and exam center details clearly.',
    format: 'PDF / JPEG',
    fileSize: 'Max 500 KB',
    states: [],
    categories: [],
    counsellingTypes: [],
  },
  {
    id: 'ol-3',
    section: 'online',
    name: 'Class 10th Marksheet & Certificate',
    mandatory: true,
    notes: 'Used for date of birth verification and name validation. Name must match NEET application exactly.',
    format: 'PDF / JPEG',
    fileSize: 'Max 300 KB',
    states: [],
    categories: [],
    counsellingTypes: [],
  },
  {
    id: 'ol-4',
    section: 'online',
    name: 'Class 12th Marksheet & Certificate',
    mandatory: true,
    notes: 'Proof of qualifying exam. Must show aggregate marks in Physics, Chemistry, Biology/Biotechnology, and English.',
    format: 'PDF / JPEG',
    fileSize: 'Max 300 KB',
    states: [],
    categories: [],
    counsellingTypes: [],
  },
  {
    id: 'ol-5',
    section: 'online',
    name: 'Passport-size Photograph',
    mandatory: true,
    notes: 'Recent photograph with white background, matching the photo uploaded during NEET registration. 3.5 cm x 4.5 cm.',
    format: 'JPEG / PNG',
    fileSize: 'Max 100 KB',
    states: [],
    categories: [],
    counsellingTypes: [],
  },
  {
    id: 'ol-6',
    section: 'online',
    name: 'Signature Scan',
    mandatory: true,
    notes: 'Scanned signature on white paper using black or blue ink. Should be clear and within the specified dimensions.',
    format: 'JPEG / PNG',
    fileSize: 'Max 50 KB',
    states: [],
    categories: [],
    counsellingTypes: [],
  },
  {
    id: 'ol-7',
    section: 'online',
    name: 'Aadhar Card / Government Photo ID',
    mandatory: true,
    notes: 'Valid, non-expired government-issued photo ID. Aadhar is universally accepted. PAN, Passport, or Voter ID are alternatives.',
    format: 'PDF / JPEG',
    fileSize: 'Max 500 KB',
    states: [],
    categories: [],
    counsellingTypes: [],
  },
  {
    id: 'ol-8',
    section: 'online',
    name: 'Category Certificate (SC/ST/OBC/EWS)',
    mandatory: true,
    notes: 'Must be issued by a competent authority (Tehsildar/SDM level or above) in the prescribed central government format. OBC certificate must have non-creamy layer clause and be issued within the last year.',
    format: 'PDF',
    fileSize: 'Max 300 KB',
    states: [],
    categories: ['SC', 'ST', 'OBC', 'EWS'],
    counsellingTypes: [],
  },
  {
    id: 'ol-9',
    section: 'online',
    name: 'PwD / Disability Certificate',
    mandatory: true,
    notes: 'Issued by a designated government medical board certifying minimum 40% disability. Must specify the type and percentage of disability.',
    format: 'PDF',
    fileSize: 'Max 300 KB',
    states: [],
    categories: ['PwD'],
    counsellingTypes: [],
  },
  {
    id: 'ol-10',
    section: 'online',
    name: 'Domicile / Residence Certificate',
    mandatory: true,
    notes: 'Required for state quota counselling. Must prove continuous residence of 10-15 years (varies by state). Issued by Tehsildar or equivalent.',
    format: 'PDF',
    fileSize: 'Max 300 KB',
    states: [],
    categories: [],
    counsellingTypes: ['State Quota'],
  },
  {
    id: 'ol-11',
    section: 'online',
    name: 'State-specific Eligibility Certificate',
    mandatory: false,
    notes: 'Some states require an additional eligibility/nativity certificate (e.g., Maharashtra requires CET Cell eligibility, Karnataka requires KEA verification). Check your state counselling portal.',
    format: 'PDF',
    fileSize: 'Max 300 KB',
    states: ['Maharashtra', 'Karnataka', 'Tamil Nadu', 'Kerala'],
    categories: [],
    counsellingTypes: ['State Quota'],
  },
  {
    id: 'ol-12',
    section: 'online',
    name: 'Income Certificate / EWS Certificate',
    mandatory: true,
    notes: 'Family annual income certificate from Tehsildar. For EWS, income must be below Rs 8 lakh/year. Valid for the current financial year only.',
    format: 'PDF',
    fileSize: 'Max 200 KB',
    states: [],
    categories: ['EWS', 'OBC'],
    counsellingTypes: [],
  },
  {
    id: 'ol-13',
    section: 'online',
    name: 'NRI / Sponsorship Letter',
    mandatory: true,
    notes: 'Sponsorship affidavit from NRI sponsor with passport copies, proof of NRI status (visa/green card), and relationship certificate.',
    format: 'PDF',
    fileSize: 'Max 1 MB',
    states: [],
    categories: [],
    counsellingTypes: ['Deemed / NRI Quota'],
  },
  {
    id: 'ol-14',
    section: 'online',
    name: 'Registration Fee Payment Receipt',
    mandatory: true,
    notes: 'Screenshot or PDF of the online payment confirmation for the counselling registration fee. Keep transaction ID handy.',
    format: 'PDF / JPEG',
    fileSize: 'Max 200 KB',
    states: [],
    categories: [],
    counsellingTypes: [],
  },

  // ───────────── PHYSICAL REPORTING DOCUMENTS ─────────────
  {
    id: 'ph-1',
    section: 'physical',
    name: 'Provisional Allotment Letter',
    mandatory: true,
    notes: 'Download from the MCC/State counselling portal after seat allotment. Print on A4 paper. This is the primary document for college reporting.',
    format: 'A4 Printout',
    fileSize: null,
    states: [],
    categories: [],
    counsellingTypes: [],
  },
  {
    id: 'ph-2',
    section: 'physical',
    name: 'NEET UG Scorecard — Original + 4 Photocopies',
    mandatory: true,
    notes: 'Carry the original scorecard and 4 attested photocopies. Some colleges require self-attestation, others need gazetted officer attestation.',
    format: 'Original + Copies',
    fileSize: null,
    states: [],
    categories: [],
    counsellingTypes: [],
  },
  {
    id: 'ph-3',
    section: 'physical',
    name: 'NEET UG Admit Card — Original',
    mandatory: true,
    notes: 'Original admit card for identity verification during physical reporting.',
    format: 'Original',
    fileSize: null,
    states: [],
    categories: [],
    counsellingTypes: [],
  },
  {
    id: 'ph-4',
    section: 'physical',
    name: 'Class 10th & 12th Originals + 4 Copies',
    mandatory: true,
    notes: 'Original marksheets and passing certificates for both 10th and 12th. Carry 4 photocopies of each. Originals will be retained by the college.',
    format: 'Original + Copies',
    fileSize: null,
    states: [],
    categories: [],
    counsellingTypes: [],
  },
  {
    id: 'ph-5',
    section: 'physical',
    name: 'Transfer Certificate (TC) from Last School',
    mandatory: true,
    notes: 'Original TC from the school/college where Class 12th was completed. Must be countersigned by the DEO/Inspector of Schools if required by the admitting college.',
    format: 'Original',
    fileSize: null,
    states: [],
    categories: [],
    counsellingTypes: [],
  },
  {
    id: 'ph-6',
    section: 'physical',
    name: 'Migration Certificate',
    mandatory: true,
    notes: 'Required if the student studied in a different state or board. Issued by the previous board of education.',
    format: 'Original',
    fileSize: null,
    states: [],
    categories: [],
    counsellingTypes: ['All India Quota (AIQ)', 'Deemed / NRI Quota'],
  },
  {
    id: 'ph-7',
    section: 'physical',
    name: 'Character / Conduct Certificate',
    mandatory: true,
    notes: 'Issued by the principal of the last attended institution. Must be recent (within 6 months).',
    format: 'Original',
    fileSize: null,
    states: [],
    categories: [],
    counsellingTypes: [],
  },
  {
    id: 'ph-8',
    section: 'physical',
    name: 'Passport-size Photographs — 10 Copies',
    mandatory: true,
    notes: 'Recent photos matching NEET application. White background, 3.5 cm x 4.5 cm. Some colleges need stamp-size photos as well.',
    format: 'Physical Prints',
    fileSize: null,
    states: [],
    categories: [],
    counsellingTypes: [],
  },
  {
    id: 'ph-9',
    section: 'physical',
    name: 'Aadhar Card — Original + 2 Copies',
    mandatory: true,
    notes: 'For identity verification and KYC during admission.',
    format: 'Original + Copies',
    fileSize: null,
    states: [],
    categories: [],
    counsellingTypes: [],
  },
  {
    id: 'ph-10',
    section: 'physical',
    name: 'Category Certificate — Original + 3 Copies',
    mandatory: true,
    notes: 'Original caste/category certificate. For OBC, non-creamy layer certificate must be current year. For EWS, income certificate required.',
    format: 'Original + Copies',
    fileSize: null,
    states: [],
    categories: ['SC', 'ST', 'OBC', 'EWS'],
    counsellingTypes: [],
  },
  {
    id: 'ph-11',
    section: 'physical',
    name: 'Domicile Certificate — Original + 2 Copies',
    mandatory: true,
    notes: 'For state quota seats. Original will be verified and returned. Ensure it matches the state of the counselling authority.',
    format: 'Original + Copies',
    fileSize: null,
    states: [],
    categories: [],
    counsellingTypes: ['State Quota'],
  },
  {
    id: 'ph-12',
    section: 'physical',
    name: 'Anti-Ragging Affidavit (Student & Parent)',
    mandatory: true,
    notes: 'Generate online from antiragging.in. Both student and parent/guardian must sign separate affidavits on Rs 100 stamp paper.',
    format: 'Stamp Paper Affidavit',
    fileSize: null,
    states: [],
    categories: [],
    counsellingTypes: [],
  },
  {
    id: 'ph-13',
    section: 'physical',
    name: 'Gap Year Affidavit',
    mandatory: false,
    notes: 'Required if there is a gap between 12th passing year and admission year. Notarized affidavit on Rs 100 stamp paper explaining the gap period.',
    format: 'Notarized Affidavit',
    fileSize: null,
    states: [],
    categories: [],
    counsellingTypes: [],
  },
  {
    id: 'ph-14',
    section: 'physical',
    name: 'Medical Fitness Certificate',
    mandatory: true,
    notes: 'Issued by a registered medical practitioner (MBBS or above). Must certify the student is medically fit for the MBBS/BDS course. Some colleges conduct their own medical exam.',
    format: 'Original',
    fileSize: null,
    states: [],
    categories: [],
    counsellingTypes: [],
  },
  {
    id: 'ph-15',
    section: 'physical',
    name: 'Demand Draft / Fee Payment Receipt',
    mandatory: true,
    notes: 'DD in favor of the college or online payment receipt for first-year fees. Confirm exact payee name and amount from allotment letter. Keep copies of all payment receipts.',
    format: 'DD / Receipt',
    fileSize: null,
    states: [],
    categories: [],
    counsellingTypes: [],
  },
  {
    id: 'ph-16',
    section: 'physical',
    name: 'Blood Group Report',
    mandatory: false,
    notes: 'Recent blood group test report from a registered pathology lab. Some colleges require this during medical exam.',
    format: 'Lab Report',
    fileSize: null,
    states: [],
    categories: [],
    counsellingTypes: [],
  },
  {
    id: 'ph-17',
    section: 'physical',
    name: 'PwD Certificate — Original + 2 Copies',
    mandatory: true,
    notes: 'Original disability certificate issued by the designated government medical board.',
    format: 'Original + Copies',
    fileSize: null,
    states: [],
    categories: ['PwD'],
    counsellingTypes: [],
  },
  {
    id: 'ph-18',
    section: 'physical',
    name: 'NRI Documents / Sponsorship Affidavit — Original',
    mandatory: true,
    notes: 'Original NRI sponsorship affidavit, passport copies of sponsor, proof of NRI status (visa/green card). Some deemed universities require embassy attestation.',
    format: 'Original + Copies',
    fileSize: null,
    states: [],
    categories: [],
    counsellingTypes: ['Deemed / NRI Quota'],
  },
];

export const CHECKLIST_FILTER_OPTIONS = {
  states: [
    'Andaman and Nicobar Islands', 'Andhra Pradesh', 'Arunachal Pradesh', 'Assam',
    'Bihar', 'Chandigarh', 'Chhattisgarh', 'Delhi', 'Goa', 'Gujarat',
    'Haryana', 'Himachal Pradesh', 'Jammu and Kashmir', 'Jharkhand',
    'Karnataka', 'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur',
    'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Puducherry', 'Punjab',
    'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura',
    'Uttar Pradesh', 'Uttarakhand', 'West Bengal',
  ],
  categories: ['General', 'SC', 'ST', 'OBC', 'EWS', 'PwD'],
  counsellingTypes: ['All India Quota (AIQ)', 'State Quota', 'Deemed / NRI Quota'],
};

// ═══════════════ STATE-WISE DOCUMENT REQUIREMENTS ═══════════════
export interface StateDocRequirement {
  checklistType: 'Form Filling' | 'Counselling' | 'College Report' | 'NRI Assistance';
  state: string;
  documents: string[];
}

export const STATE_WISE_DOCS: StateDocRequirement[] = [
  {
    checklistType: 'Form Filling',
    state: 'Andaman and Nicobar Islands',
    documents: [
      'Recent passport-size photograph (same as used in NEET UG application form and Hall Ticket)',
      'Scanned signature of the candidate',
      'NEET UG Admit Card (issued by NTA)',
      'NEET UG Score Card / Result / Rank Letter',
      'Date of Birth Certificate (Class 10 Board Certificate or Birth Certificate)',
      'Class 10 Mark Sheet and Passing Certificate',
      'Class 12 Mark Sheet and Passing Certificate',
      'Category Certificate — SC/ST/OBC-NCL/EWS/PwBD (if applicable), issued by competent authority',
      'Tribal Certificate (for Category-I candidates), as per prescribed format',
      'Employer Certificate for Deputationist/Central Government Service (for Category-II candidates)',
      'Settler Certificate / Rehabilitation Scheme Certificate (for Category-III candidates)',
      'Islander Card / Permanent Resident / Domicile Certificate (for Category-IV candidates)',
      'School Certificate / Transfer Certificate proving last 2 years of study in the Islands',
      'PwBD Certificate (if applicable), issued by CMO/Civil Surgeon',
      'Migration Certificate (if applicable)',
      'Character Certificate from the institution last attended',
      'Aadhar Card / Government-issued Photo ID',
      'Passport (for NRI/OCI candidates)',
      'NRI Sponsor\'s Passport + Visa copy (for NRI category)',
      'OCI Card (for OCI candidates)',
    ],
  },
  {
    checklistType: 'Form Filling',
    state: 'Maharashtra',
    documents: [
      'Recent passport-size photograph (white background)',
      'Scanned signature of the candidate',
      'NEET UG Admit Card (issued by NTA)',
      'NEET UG Score Card / Result / Rank Letter',
      'Class 10 Mark Sheet and Passing Certificate',
      'Class 12 Mark Sheet and Passing Certificate',
      'CET Cell Eligibility Certificate (mandatory for state quota)',
      'Domicile Certificate issued by Tehsildar',
      'Caste Certificate (SC/ST/OBC/SBC/VJ-NT) issued by competent authority',
      'Caste Validity Certificate (for reserved categories)',
      'Non-Creamy Layer Certificate (for OBC/SBC/VJ-NT, valid for current year)',
      'EWS Certificate (if applicable, income below Rs 8 lakh)',
      'PwBD Certificate (if applicable)',
      'Aadhar Card / Government-issued Photo ID',
      'Registration Fee Payment Receipt',
      'Gap Year Affidavit (if applicable)',
    ],
  },
  {
    checklistType: 'Form Filling',
    state: 'Karnataka',
    documents: [
      'Recent passport-size photograph (white background)',
      'Scanned signature of the candidate',
      'NEET UG Admit Card (issued by NTA)',
      'NEET UG Score Card / Result / Rank Letter',
      'Class 10 Mark Sheet and Passing Certificate (SSLC)',
      'Class 12 Mark Sheet and Passing Certificate (PUC II)',
      'KEA Verification Certificate (mandatory for state quota)',
      'Domicile / Residence Certificate (7 years continuous residence)',
      'Study Certificate from Class 1 to 10 in Karnataka',
      'Category Certificate (SC/ST/OBC/Cat-I/IIA/IIB/IIIA/IIIB)',
      'Income Certificate (for fee concession / EWS)',
      'Rural Study Certificate (for rural quota, if applicable)',
      'Kannada Medium Study Certificate (for Kannada medium quota)',
      'PwBD Certificate (if applicable)',
      'Aadhar Card / Government-issued Photo ID',
      'Registration Fee Payment Receipt',
    ],
  },
  {
    checklistType: 'Form Filling',
    state: 'Tamil Nadu',
    documents: [
      'Recent passport-size photograph (white background)',
      'Scanned signature of the candidate',
      'NEET UG Admit Card (issued by NTA)',
      'NEET UG Score Card / Result / Rank Letter',
      'Class 10 Mark Sheet and Passing Certificate',
      'Class 12 Mark Sheet and Passing Certificate (HSC)',
      'Nativity / Permanent Resident Certificate issued by Tahsildar',
      'Community Certificate (BC/MBC/SC/ST/SCA) issued by Revenue Divisional Officer',
      'Income Certificate (for fee waiver under free education scheme)',
      'First Graduate Certificate (if applicable, for 7.5% govt school quota)',
      'Govt School Study Certificate (for 7.5% reservation)',
      'PwBD Certificate (if applicable)',
      'Aadhar Card / Government-issued Photo ID',
      'Registration Fee Payment Receipt',
      'Sri Lankan Tamil Refugee Certificate (if applicable)',
    ],
  },
  {
    checklistType: 'Form Filling',
    state: 'Kerala',
    documents: [
      'Recent passport-size photograph (white background)',
      'Scanned signature of the candidate',
      'NEET UG Admit Card (issued by NTA)',
      'NEET UG Score Card / Result / Rank Letter',
      'Class 10 Mark Sheet (SSLC) and Passing Certificate',
      'Class 12 Mark Sheet and Passing Certificate (Plus Two)',
      'Nativity Certificate issued by Village Officer',
      'Community / Caste Certificate (for SC/ST/OBC/SEBC)',
      'Non-Creamy Layer Certificate (for OBC, current year)',
      'Income Certificate (for EWS / fee concession)',
      'NRI Documents — Sponsor\'s Passport, Visa, Relationship Certificate (for NRI quota)',
      'PwBD Certificate (if applicable)',
      'Aadhar Card / Government-issued Photo ID',
      'Registration Fee Payment Receipt',
    ],
  },
  {
    checklistType: 'Form Filling',
    state: 'Delhi',
    documents: [
      'Recent passport-size photograph (white background)',
      'Scanned signature of the candidate',
      'NEET UG Admit Card (issued by NTA)',
      'NEET UG Score Card / Result / Rank Letter',
      'Class 10 Mark Sheet and Passing Certificate',
      'Class 12 Mark Sheet and Passing Certificate',
      'Delhi Domicile Certificate / Self-declaration (3 years residence)',
      'Category Certificate (SC/ST/OBC) issued by competent Delhi authority',
      'EWS Certificate (if applicable)',
      'PwBD Certificate (if applicable)',
      'Aadhar Card / Government-issued Photo ID',
      'Registration Fee Payment Receipt',
      'IPU Registration Confirmation (for IPU colleges)',
    ],
  },
  {
    checklistType: 'Form Filling',
    state: 'Uttar Pradesh',
    documents: [
      'Recent passport-size photograph (white background)',
      'Scanned signature of the candidate',
      'NEET UG Admit Card (issued by NTA)',
      'NEET UG Score Card / Result / Rank Letter',
      'Class 10 Mark Sheet (High School) and Passing Certificate',
      'Class 12 Mark Sheet (Intermediate) and Passing Certificate',
      'Domicile Certificate of Uttar Pradesh (issued by Tehsildar/SDM)',
      'Category Certificate (SC/ST/OBC) issued by competent authority',
      'Income Certificate (for EWS / fee concession, from Tehsildar)',
      'Freedom Fighter Certificate (if applicable)',
      'PwBD Certificate (if applicable)',
      'Aadhar Card / Government-issued Photo ID',
      'Registration Fee Payment Receipt',
    ],
  },
  {
    checklistType: 'Form Filling',
    state: 'Gujarat',
    documents: [
      'Recent passport-size photograph (white background)',
      'Scanned signature of the candidate',
      'NEET UG Admit Card (issued by NTA)',
      'NEET UG Score Card / Result / Rank Letter',
      'Class 10 Mark Sheet and Passing Certificate',
      'Class 12 Mark Sheet and Passing Certificate (HSC)',
      'Domicile Certificate of Gujarat (issued by Mamlatdar)',
      'Category Certificate (SC/ST/SEBC/EWS) issued by competent authority',
      'Non-Creamy Layer Certificate (for SEBC, current year)',
      'PwBD Certificate (if applicable)',
      'Aadhar Card / Government-issued Photo ID',
      'ACPUGMEC Registration Fee Payment Receipt',
    ],
  },
  {
    checklistType: 'Form Filling',
    state: 'Rajasthan',
    documents: [
      'Recent passport-size photograph (white background)',
      'Scanned signature of the candidate',
      'NEET UG Admit Card (issued by NTA)',
      'NEET UG Score Card / Result / Rank Letter',
      'Class 10 Mark Sheet and Passing Certificate',
      'Class 12 Mark Sheet and Passing Certificate',
      'Domicile / Bonafide Certificate of Rajasthan',
      'Category Certificate (SC/ST/OBC/MBC/EWS) issued by Tehsildar',
      'Non-Creamy Layer Certificate (for OBC/MBC, current year)',
      'Income Certificate (for EWS)',
      'PwBD Certificate (if applicable)',
      'Aadhar Card / Government-issued Photo ID',
      'Registration Fee Payment Receipt',
    ],
  },
  {
    checklistType: 'Form Filling',
    state: 'Telangana',
    documents: [
      'Recent passport-size photograph (white background)',
      'Scanned signature of the candidate',
      'NEET UG Admit Card (issued by NTA)',
      'NEET UG Score Card / Result / Rank Letter',
      'Class 10 Mark Sheet (SSC) and Passing Certificate',
      'Class 12 Mark Sheet (Intermediate) and Passing Certificate',
      'Study Certificate from Class 4 to 12 in Telangana',
      'Local / Non-Local Status Certificate',
      'Integrated Community Certificate (for BC/SC/ST) from MeeSeva',
      'EWS Certificate (if applicable)',
      'PwBD Certificate (if applicable)',
      'Aadhar Card / Government-issued Photo ID',
      'KNRUHS Registration Fee Payment Receipt',
    ],
  },
  {
    checklistType: 'Counselling',
    state: 'Maharashtra',
    documents: [
      'Allotment Letter / Provisional Admission Letter from CET Cell',
      'Original NEET Scorecard + 4 attested photocopies',
      'Original Class 10 & 12 Marksheets + Certificates',
      'CET Cell Eligibility Certificate (Original)',
      'Domicile Certificate (Original)',
      'Caste Certificate + Caste Validity Certificate (Original, for reserved categories)',
      'Transfer Certificate from last attended institution',
      'Migration Certificate (if from another board/state)',
      'Anti-Ragging Affidavit (from antiragging.in)',
      'Medical Fitness Certificate',
      'Passport-size Photographs (10 copies)',
      'Demand Draft / Fee Payment Receipt for first-year fees',
    ],
  },
  {
    checklistType: 'Counselling',
    state: 'Karnataka',
    documents: [
      'KEA Allotment Order / Admission Order',
      'Original NEET Scorecard + 4 attested photocopies',
      'Original SSLC & PUC II Marksheets + Certificates',
      'KEA Verification Certificate (Original)',
      'Study Certificate (1st to 10th standard in Karnataka)',
      'Category Certificate (Original, for reserved categories)',
      'Income Certificate (for fee concession)',
      'Transfer Certificate from last attended institution',
      'Migration Certificate (if applicable)',
      'Anti-Ragging Affidavit (from antiragging.in)',
      'Medical Fitness Certificate',
      'Passport-size Photographs (10 copies)',
      'Fee Payment Receipt / DD for first-year fees',
    ],
  },
  {
    checklistType: 'NRI Assistance',
    state: 'Maharashtra',
    documents: [
      'NRI Sponsor\'s valid Passport (original + attested copy)',
      'NRI Sponsor\'s valid Visa / Green Card / Work Permit',
      'Proof of NRI Status (employment letter, tax returns from abroad)',
      'Relationship Certificate between sponsor and candidate',
      'Sponsorship Affidavit on stamp paper (notarized)',
      'Bank Statement of NRI sponsor (last 6 months)',
      'Candidate\'s Passport (if available)',
      'Candidate\'s NEET UG Scorecard',
      'All academic documents (Class 10, 12 marksheets)',
    ],
  },
  {
    checklistType: 'NRI Assistance',
    state: 'Karnataka',
    documents: [
      'NRI Sponsor\'s valid Passport (original + attested copy)',
      'NRI Sponsor\'s Employment Visa / Work Permit / Green Card',
      'Relationship Certificate (from Indian Embassy or Tehsildar)',
      'Sponsorship Affidavit on Rs 200 stamp paper (notarized)',
      'Bank statements showing NRI income (last 12 months)',
      'Candidate\'s academic documents (SSLC, PUC II marksheets)',
      'Candidate\'s NEET UG Scorecard and Admit Card',
      'KEA NRI Quota Application Form',
    ],
  },
];
