export type ChecklistSection = 'online' | 'physical';

export interface ChecklistDoc {
  id: string;
  section: ChecklistSection;
  name: string;
  mandatory: boolean;
  notes: string;
  format: string;
  fileSize: string | null;
  states: string[];       // empty = all states
  categories: string[];   // empty = all categories
  counsellingTypes: string[]; // empty = all types
}

export const CHECKLIST_DOCS: ChecklistDoc[] = [
  // ───────────── ONLINE REGISTRATION DOCUMENTS ─────────────
  {
    id: 'ol-1',
    section: 'online',
    name: 'NEET UG Scorecard / Rank Letter',
    mandatory: true,
    notes: 'Download the official scorecard from nta.ac.in. Both scorecard and rank letter are needed. Ensure the PDF is clear and legible.',
    format: 'PDF / JPEG',
    fileSize: 'Max 500 KB',
    states: [],
    categories: [],
    counsellingTypes: [],
  },
  {
    id: 'ol-2',
    section: 'online',
    name: 'NEET UG Admit Card',
    mandatory: true,
    notes: 'The admit card used during the NEET exam. Must show photograph, roll number, and exam center details clearly.',
    format: 'PDF / JPEG',
    fileSize: 'Max 500 KB',
    states: [],
    categories: [],
    counsellingTypes: [],
  },
  {
    id: 'ol-3',
    section: 'online',
    name: 'Class 10th Marksheet & Certificate',
    mandatory: true,
    notes: 'Used for date of birth verification and name validation. Name must match NEET application exactly.',
    format: 'PDF / JPEG',
    fileSize: 'Max 300 KB',
    states: [],
    categories: [],
    counsellingTypes: [],
  },
  {
    id: 'ol-4',
    section: 'online',
    name: 'Class 12th Marksheet & Certificate',
    mandatory: true,
    notes: 'Proof of qualifying exam. Must show aggregate marks in Physics, Chemistry, Biology/Biotechnology, and English.',
    format: 'PDF / JPEG',
    fileSize: 'Max 300 KB',
    states: [],
    categories: [],
    counsellingTypes: [],
  },
  {
    id: 'ol-5',
    section: 'online',
    name: 'Passport-size Photograph',
    mandatory: true,
    notes: 'Recent photograph with white background, matching the photo uploaded during NEET registration. 3.5 cm x 4.5 cm.',
    format: 'JPEG / PNG',
    fileSize: 'Max 100 KB',
    states: [],
    categories: [],
    counsellingTypes: [],
  },
  {
    id: 'ol-6',
    section: 'online',
    name: 'Signature Scan',
    mandatory: true,
    notes: 'Scanned signature on white paper using black or blue ink. Should be clear and within the specified dimensions.',
    format: 'JPEG / PNG',
    fileSize: 'Max 50 KB',
    states: [],
    categories: [],
    counsellingTypes: [],
  },
  {
    id: 'ol-7',
    section: 'online',
    name: 'Aadhar Card / Government Photo ID',
    mandatory: true,
    notes: 'Valid, non-expired government-issued photo ID. Aadhar is universally accepted. PAN, Passport, or Voter ID are alternatives.',
    format: 'PDF / JPEG',
    fileSize: 'Max 500 KB',
    states: [],
    categories: [],
    counsellingTypes: [],
  },
  {
    id: 'ol-8',
    section: 'online',
    name: 'Category Certificate (SC/ST/OBC/EWS)',
    mandatory: true,
    notes: 'Must be issued by a competent authority (Tehsildar/SDM level or above) in the prescribed central government format. OBC certificate must have non-creamy layer clause and be issued within the last year.',
    format: 'PDF',
    fileSize: 'Max 300 KB',
    states: [],
    categories: ['SC', 'ST', 'OBC', 'EWS'],
    counsellingTypes: [],
  },
  {
    id: 'ol-9',
    section: 'online',
    name: 'PwD / Disability Certificate',
    mandatory: true,
    notes: 'Issued by a designated government medical board certifying minimum 40% disability. Must specify the type and percentage of disability.',
    format: 'PDF',
    fileSize: 'Max 300 KB',
    states: [],
    categories: ['PwD'],
    counsellingTypes: [],
  },
  {
    id: 'ol-10',
    section: 'online',
    name: 'Domicile / Residence Certificate',
    mandatory: true,
    notes: 'Required for state quota counselling. Must prove continuous residence of 10-15 years (varies by state). Issued by Tehsildar or equivalent.',
    format: 'PDF',
    fileSize: 'Max 300 KB',
    states: [],
    categories: [],
    counsellingTypes: ['State Quota'],
  },
  {
    id: 'ol-11',
    section: 'online',
    name: 'State-specific Eligibility Certificate',
    mandatory: false,
    notes: 'Some states require an additional eligibility/nativity certificate (e.g., Maharashtra requires CET Cell eligibility, Karnataka requires KEA verification). Check your state counselling portal.',
    format: 'PDF',
    fileSize: 'Max 300 KB',
    states: ['Maharashtra', 'Karnataka', 'Tamil Nadu', 'Kerala'],
    categories: [],
    counsellingTypes: ['State Quota'],
  },
  {
    id: 'ol-12',
    section: 'online',
    name: 'Income Certificate / EWS Certificate',
    mandatory: true,
    notes: 'Family annual income certificate from Tehsildar. For EWS, income must be below Rs 8 lakh/year. Valid for the current financial year only.',
    format: 'PDF',
    fileSize: 'Max 200 KB',
    states: [],
    categories: ['EWS', 'OBC'],
    counsellingTypes: [],
  },
  {
    id: 'ol-13',
    section: 'online',
    name: 'NRI / Sponsorship Letter',
    mandatory: true,
    notes: 'Sponsorship affidavit from NRI sponsor with passport copies, proof of NRI status (visa/green card), and relationship certificate.',
    format: 'PDF',
    fileSize: 'Max 1 MB',
    states: [],
    categories: [],
    counsellingTypes: ['Deemed / NRI Quota'],
  },
  {
    id: 'ol-14',
    section: 'online',
    name: 'Registration Fee Payment Receipt',
    mandatory: true,
    notes: 'Screenshot or PDF of the online payment confirmation for the counselling registration fee. Keep transaction ID handy.',
    format: 'PDF / JPEG',
    fileSize: 'Max 200 KB',
    states: [],
    categories: [],
    counsellingTypes: [],
  },

  // ───────────── PHYSICAL REPORTING DOCUMENTS ─────────────
  {
    id: 'ph-1',
    section: 'physical',
    name: 'Provisional Allotment Letter',
    mandatory: true,
    notes: 'Download from the MCC/State counselling portal after seat allotment. Print on A4 paper. This is the primary document for college reporting.',
    format: 'A4 Printout',
    fileSize: null,
    states: [],
    categories: [],
    counsellingTypes: [],
  },
  {
    id: 'ph-2',
    section: 'physical',
    name: 'NEET UG Scorecard — Original + 4 Photocopies',
    mandatory: true,
    notes: 'Carry the original scorecard and 4 attested photocopies. Some colleges require self-attestation, others need gazetted officer attestation.',
    format: 'Original + Copies',
    fileSize: null,
    states: [],
    categories: [],
    counsellingTypes: [],
  },
  {
    id: 'ph-3',
    section: 'physical',
    name: 'NEET UG Admit Card — Original',
    mandatory: true,
    notes: 'Original admit card for identity verification during physical reporting.',
    format: 'Original',
    fileSize: null,
    states: [],
    categories: [],
    counsellingTypes: [],
  },
  {
    id: 'ph-4',
    section: 'physical',
    name: 'Class 10th & 12th Originals + 4 Copies',
    mandatory: true,
    notes: 'Original marksheets and passing certificates for both 10th and 12th. Carry 4 photocopies of each. Originals will be retained by the college.',
    format: 'Original + Copies',
    fileSize: null,
    states: [],
    categories: [],
    counsellingTypes: [],
  },
  {
    id: 'ph-5',
    section: 'physical',
    name: 'Transfer Certificate (TC) from Last School',
    mandatory: true,
    notes: 'Original TC from the school/college where Class 12th was completed. Must be countersigned by the DEO/Inspector of Schools if required by the admitting college.',
    format: 'Original',
    fileSize: null,
    states: [],
    categories: [],
    counsellingTypes: [],
  },
  {
    id: 'ph-6',
    section: 'physical',
    name: 'Migration Certificate',
    mandatory: true,
    notes: 'Required if the student studied in a different state or board. Issued by the previous board of education.',
    format: 'Original',
    fileSize: null,
    states: [],
    categories: [],
    counsellingTypes: ['All India Quota (AIQ)', 'Deemed / NRI Quota'],
  },
  {
    id: 'ph-7',
    section: 'physical',
    name: 'Character / Conduct Certificate',
    mandatory: true,
    notes: 'Issued by the principal of the last attended institution. Must be recent (within 6 months).',
    format: 'Original',
    fileSize: null,
    states: [],
    categories: [],
    counsellingTypes: [],
  },
  {
    id: 'ph-8',
    section: 'physical',
    name: 'Passport-size Photographs — 10 Copies',
    mandatory: true,
    notes: 'Recent photos matching NEET application. White background, 3.5 cm x 4.5 cm. Some colleges need stamp-size photos as well.',
    format: 'Physical Prints',
    fileSize: null,
    states: [],
    categories: [],
    counsellingTypes: [],
  },
  {
    id: 'ph-9',
    section: 'physical',
    name: 'Aadhar Card — Original + 2 Copies',
    mandatory: true,
    notes: 'For identity verification and KYC during admission.',
    format: 'Original + Copies',
    fileSize: null,
    states: [],
    categories: [],
    counsellingTypes: [],
  },
  {
    id: 'ph-10',
    section: 'physical',
    name: 'Category Certificate — Original + 3 Copies',
    mandatory: true,
    notes: 'Original caste/category certificate. For OBC, non-creamy layer certificate must be current year. For EWS, income certificate required.',
    format: 'Original + Copies',
    fileSize: null,
    states: [],
    categories: ['SC', 'ST', 'OBC', 'EWS'],
    counsellingTypes: [],
  },
  {
    id: 'ph-11',
    section: 'physical',
    name: 'Domicile Certificate — Original + 2 Copies',
    mandatory: true,
    notes: 'For state quota seats. Original will be verified and returned. Ensure it matches the state of the counselling authority.',
    format: 'Original + Copies',
    fileSize: null,
    states: [],
    categories: [],
    counsellingTypes: ['State Quota'],
  },
  {
    id: 'ph-12',
    section: 'physical',
    name: 'Anti-Ragging Affidavit (Student & Parent)',
    mandatory: true,
    notes: 'Generate online from antiragging.in. Both student and parent/guardian must sign separate affidavits on Rs 100 stamp paper.',
    format: 'Stamp Paper Affidavit',
    fileSize: null,
    states: [],
    categories: [],
    counsellingTypes: [],
  },
  {
    id: 'ph-13',
    section: 'physical',
    name: 'Gap Year Affidavit',
    mandatory: false,
    notes: 'Required if there is a gap between 12th passing year and admission year. Notarized affidavit on Rs 100 stamp paper explaining the gap period.',
    format: 'Notarized Affidavit',
    fileSize: null,
    states: [],
    categories: [],
    counsellingTypes: [],
  },
  {
    id: 'ph-14',
    section: 'physical',
    name: 'Medical Fitness Certificate',
    mandatory: true,
    notes: 'Issued by a registered medical practitioner (MBBS or above). Must certify the student is medically fit for the MBBS/BDS course. Some colleges conduct their own medical exam.',
    format: 'Original',
    fileSize: null,
    states: [],
    categories: [],
    counsellingTypes: [],
  },
  {
    id: 'ph-15',
    section: 'physical',
    name: 'Demand Draft / Fee Payment Receipt',
    mandatory: true,
    notes: 'DD in favor of the college or online payment receipt for first-year fees. Confirm exact payee name and amount from allotment letter. Keep copies of all payment receipts.',
    format: 'DD / Receipt',
    fileSize: null,
    states: [],
    categories: [],
    counsellingTypes: [],
  },
  {
    id: 'ph-16',
    section: 'physical',
    name: 'Blood Group Report',
    mandatory: false,
    notes: 'Recent blood group test report from a registered pathology lab. Some colleges require this during medical exam.',
    format: 'Lab Report',
    fileSize: null,
    states: [],
    categories: [],
    counsellingTypes: [],
  },
  {
    id: 'ph-17',
    section: 'physical',
    name: 'PwD Certificate — Original + 2 Copies',
    mandatory: true,
    notes: 'Original disability certificate issued by the designated government medical board.',
    format: 'Original + Copies',
    fileSize: null,
    states: [],
    categories: ['PwD'],
    counsellingTypes: [],
  },
  {
    id: 'ph-18',
    section: 'physical',
    name: 'NRI Documents / Sponsorship Affidavit — Original',
    mandatory: true,
    notes: 'Original NRI sponsorship affidavit, passport copies of sponsor, proof of NRI status (visa/green card). Some deemed universities require embassy attestation.',
    format: 'Original + Copies',
    fileSize: null,
    states: [],
    categories: [],
    counsellingTypes: ['Deemed / NRI Quota'],
  },
];

export const CHECKLIST_FILTER_OPTIONS = {
  states: ['Maharashtra', 'Karnataka', 'Tamil Nadu', 'Kerala', 'Delhi'],
  categories: ['General', 'SC', 'ST', 'OBC', 'EWS', 'PwD'],
  counsellingTypes: ['All India Quota (AIQ)', 'State Quota', 'Deemed / NRI Quota'],
};
