import type { CounselingNotification } from '@/services/notification.service';
import type { CutoffEntry } from '@/services/cutoff.service';
import type { DocumentEntry } from '@/services/document.service';

export const MOCK_NOTIFICATIONS: CounselingNotification[] = [
  {
    id: 'mock-1',
    title: 'MCC NEET UG 2026 Round 1 Seat Matrix Released',
    summary:
      'Official seat matrix for 15% All India Quota, Deemed, and Central Universities MBBS/BDS/B.Sc Nursing choices published by MCC.',
    content:
      'All eligible NEET UG 2026 aspirants are hereby informed that the Round 1 Seat Matrix has been uploaded. Aspirants can now evaluate their choices based on closing ranks from previous years. Choice filling starts on July 18, 2026.\n\nCandidates must select their preferences with extreme care. Once locked, choices cannot be modified. Refer to the seat availability pdf attached below for detailed count of college and category seats.',
    translationHi:
      'MCC NEET UG 2026 प्रथम दौर की सीट मैट्रिक्स जारी कर दी गई है। सभी योग्य उम्मीदवार आधिकारिक वेबसाइट पर रिक्त सीटों की सूची देख सकते हैं। उम्मीदवारों को सलाह दी जाती है कि वे अपने विकल्पों का चयन बहुत सावधानी से करें। लॉक होने के बाद विकल्पों में बदलाव नहीं किया जा सकता है।',
    state: 'All India',
    category: 'Seat Matrix' as const,
    counselingBody: 'MCC',
    pdfUrl: '/mock-pdfs/seat-matrix.pdf',
    pdfOriginalName: 'MCC_R1_SeatMatrix_2026.pdf',
    sourceUrl: 'https://mcc.nic.in',
    priority: 'high' as const,
    isPublished: true,
    publishedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    isBookmarked: false,
    bookmarkCount: 15,
  },
  {
    id: 'mock-2',
    title: 'KEA Karnataka NEET UG Online Registration Schedule Out',
    summary:
      'Karnataka Examinations Authority (KEA) opens online registration and document upload portal for MBBS/BDS admission 2026.',
    content:
      'KEA Karnataka has activated the application link. Domicile certificates, NEET scorecards, and class 10/12 marks sheets must be uploaded by July 10, 2026, to qualify for state quota counseling.',
    translationHi:
      'KEA कर्नाटक NEET UG ऑनलाइन पंजीकरण कार्यक्रम जारी। आवेदन करने की अंतिम तिथि 10 जुलाई, 2026 है। कृपया आवश्यक दस्तावेज जैसे अधिवास प्रमाण पत्र और अंक पत्र तैयार रखें।',
    state: 'Karnataka',
    category: 'Schedule' as const,
    counselingBody: 'KEA',
    pdfUrl: null,
    pdfOriginalName: null,
    sourceUrl: 'https://cetonline.karnataka.gov.in/kea/',
    priority: 'urgent' as const,
    isPublished: true,
    publishedAt: new Date(Date.now() - 3600000 * 5).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    isBookmarked: true,
    bookmarkCount: 42,
  },
  {
    id: 'mock-3',
    title: 'CET Cell Maharashtra Medical Brochure & Eligibility Criteria',
    summary:
      'Maharashtra State CET Cell publishes official prospectus containing domicile categories (A/B/C) and reservation percentages.',
    content:
      'Read this document carefully to determine state quota eligibility. Domicile rules apply strictly for 85% state seats in government and private colleges.',
    translationHi:
      'महाराष्ट्र मेडिकल ब्रोशर और पात्रता मानदंड जारी किए गए हैं। अधिवास नियमों का विवरण पढ़ें। सरकारी और निजी कॉलेजों में राज्य कोटे के लिए अधिवास नियम कड़े हैं।',
    state: 'Maharashtra',
    category: 'General' as const,
    counselingBody: 'CET Cell',
    pdfUrl: null,
    pdfOriginalName: null,
    sourceUrl: 'https://cetcell.mahacet.org',
    priority: 'normal' as const,
    isPublished: true,
    publishedAt: new Date(Date.now() - 3600000 * 24).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    isBookmarked: false,
    bookmarkCount: 8,
  },
];

export const MOCK_CUTOFFS: CutoffEntry[] = [
  {
    id: 'mock-c-1',
    collegeId: 'col-1',
    college: {
      id: 'col-1',
      name: 'All India Institute of Medical Sciences (AIIMS), New Delhi',
      state: 'Delhi',
      city: 'New Delhi',
      type: 'Government',
      totalSeats: 125,
      website: 'https://www.aiimsexams.ac.in',
      isActive: true,
    },
    year: 2025,
    round: 1,
    course: 'MBBS',
    quota: 'All India Quota (AIQ)',
    category: 'General',
    subcategory: 'Open',
    seatType: 'Government Seat',
    air: 57,
    score: 715,
    fees: 1628,
  },
  {
    id: 'mock-c-2',
    collegeId: 'col-2',
    college: {
      id: 'col-2',
      name: 'Maulana Azad Medical College (MAMC), New Delhi',
      state: 'Delhi',
      city: 'New Delhi',
      type: 'Government',
      totalSeats: 250,
      website: 'https://mamc.delhi.gov.in',
      isActive: true,
    },
    year: 2025,
    round: 1,
    course: 'MBBS',
    quota: 'Delhi State Quota',
    category: 'General',
    subcategory: 'Open',
    seatType: 'Government Seat',
    air: 85,
    score: 710,
    fees: 4445,
  },
  {
    id: 'mock-c-3',
    collegeId: 'col-3',
    college: {
      id: 'col-3',
      name: 'Grant Medical College & Sir JJ Group of Hospitals, Mumbai',
      state: 'Maharashtra',
      city: 'Mumbai',
      type: 'Government',
      totalSeats: 250,
      website: 'https://gmcjjh.org',
      isActive: true,
    },
    year: 2025,
    round: 1,
    course: 'MBBS',
    quota: 'Maharashtra State Quota',
    category: 'OBC',
    subcategory: 'Open',
    seatType: 'Government Seat',
    air: 1824,
    score: 685,
    fees: 135000,
  },
  {
    id: 'mock-c-4',
    collegeId: 'col-4',
    college: {
      id: 'col-4',
      name: 'Bangalore Medical College and Research Institute (BMCRI)',
      state: 'Karnataka',
      city: 'Bengaluru',
      type: 'Government',
      totalSeats: 250,
      website: 'https://bmcri.karnataka.gov.in',
      isActive: true,
    },
    year: 2025,
    round: 2,
    course: 'MBBS',
    quota: 'Karnataka State Quota',
    category: 'General',
    subcategory: 'Open',
    seatType: 'Government Seat',
    air: 945,
    score: 695,
    fees: 70150,
  },
  {
    id: 'mock-c-5',
    collegeId: 'col-5',
    college: {
      id: 'col-5',
      name: 'Kasturba Medical College (KMC), Manipal',
      state: 'Karnataka',
      city: 'Manipal',
      type: 'Deemed',
      totalSeats: 250,
      website: 'https://manipal.edu',
      isActive: true,
    },
    year: 2025,
    round: 1,
    course: 'MBBS',
    quota: 'Management Quota',
    category: 'General',
    subcategory: 'None',
    seatType: 'Management Seat',
    air: 42150,
    score: 565,
    fees: 1780000,
  },
  {
    id: 'mock-c-6',
    collegeId: 'col-6',
    college: {
      id: 'col-6',
      name: 'Christian Medical College (CMC), Vellore',
      state: 'Tamil Nadu',
      city: 'Vellore',
      type: 'Private',
      totalSeats: 100,
      website: 'https://www.cmcvellore.ac.in',
      isActive: true,
    },
    year: 2025,
    round: 1,
    course: 'MBBS',
    quota: 'Management Quota',
    category: 'SC',
    subcategory: 'Open',
    seatType: 'Private Seat',
    air: 5410,
    score: 662,
    fees: 52000,
  },
  {
    id: 'mock-c-7',
    collegeId: 'col-7',
    college: {
      id: 'col-7',
      name: 'Lokmanya Tilak Municipal Medical College (LTMMC), Mumbai',
      state: 'Maharashtra',
      city: 'Sion, Mumbai',
      type: 'Government',
      totalSeats: 200,
      website: 'https://ltmgh.com',
      isActive: true,
    },
    year: 2025,
    round: 2,
    course: 'BDS',
    quota: 'Maharashtra State Quota',
    category: 'General',
    subcategory: 'Open',
    seatType: 'Government Seat',
    air: 15420,
    score: 615,
    fees: 114000,
  },
];

export const MOCK_DOCUMENTS: DocumentEntry[] = [
  {
    id: 'mock-doc-1',
    name: 'NEET Admit Card',
    description: 'Admit card issued by NTA for the NEET examination.',
    state: null,
    category: null,
    isRequired: true,
    notes: 'Must bring the original and multiple photocopies. Color printout is preferred.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'mock-doc-2',
    name: 'NEET Rank Letter/Scorecard',
    description: "Scorecard issued by NTA showing the candidate's AIR and percentile.",
    state: null,
    category: null,
    isRequired: true,
    notes: 'Download from the NTA website.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'mock-doc-3',
    name: 'Class 10 Certificate & Marksheet',
    description: 'Used for birth date verification and identity proof.',
    state: null,
    category: null,
    isRequired: true,
    notes: 'Name should strictly match the NEET admit card.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'mock-doc-4',
    name: 'Class 12 Certificate & Marksheet',
    description: 'Proof of qualifying examination.',
    state: null,
    category: null,
    isRequired: true,
    notes: 'Must have passed with required aggregate in PCB and English.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'mock-doc-5',
    name: 'ID Proof (Aadhar/PAN/Driving License/Passport)',
    description: 'Valid, non-expired, government-issued photo ID.',
    state: null,
    category: null,
    isRequired: true,
    notes: 'Aadhar card is universally accepted and preferred.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'mock-doc-6',
    name: 'Passport Size Photographs',
    description: 'Recent passport size photographs.',
    state: null,
    category: null,
    isRequired: true,
    notes: 'Usually 8-10 copies are required. Should match the photo uploaded during NEET application.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'mock-doc-7',
    name: 'Provisional Allotment Letter',
    description: 'Letter generated online after the counseling result declaration.',
    state: null,
    category: null,
    isRequired: true,
    notes: 'Download from the MCC/State Counseling website.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'mock-doc-8',
    name: 'Caste Certificate',
    description: 'Required if claiming reservation under SC/ST/OBC/EWS category.',
    state: null,
    category: 'Category',
    isRequired: false,
    notes: 'Must be issued by a competent authority in the prescribed format.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'mock-doc-9',
    name: 'Domicile Certificate',
    description: 'Proof of residence for State Quota seats.',
    state: 'All States',
    category: 'State Quota',
    isRequired: false,
    notes: 'Requirements vary by state (e.g., 10-15 years continuous residence, or passed 10th/12th from the state).',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'mock-doc-10',
    name: 'Gap Certificate',
    description: 'Affidavit explaining any gap years between 12th passing and admission.',
    state: null,
    category: 'General',
    isRequired: false,
    notes: 'Format usually available on a ₹100 stamp paper.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
